### ISSUE TITLE
ABPresence OSX app doesn't build with RM 2.20

### ISSUE THREAD

**Issue by tsugua** [HipByte/RubyMotionSamples#39]
```
from /Library/RubyMotion/lib/motion/../../bin/motion:12:in `<main>'
 Build ./build/MacOSX-10.9-Development
   Run ./build/MacOSX-10.9-Development/ABPresence.app/Contents/MacOS/ABPresence
```

2014-01-29 22:42:35.197 ABPresence[77294:303] service_watcher.rb:9:in `startMonitoring': undefined method`addObserver' for nil:NilClass (NoMethodError)
    from people_controller.rb:39:in `initialize:'
    from app_delegate.rb:13:in`buildWindow'
    from app_delegate.rb:4:in `applicationDidFinishLaunching:'
2014-01-29 22:42:35.197 ABPresence[77294:303] *nil description*
(main)> rake -trace
2014-01-29 22:42:55.068 ABPresence[77294:303] undefined local variable or method`trace' for main:TopLevel (NameError)
=> #<NameError: undefined local variable or method `trace' for main:TopLevel>
(main)> rake -tShauns-Laptop:ABPresence shaun$ rake -trace
rake aborted!
Unrecognized --trace option 'race'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:563:in `select_trace_output'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:517:in`block in standard_rake_options'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/optparse.rb:1391:in `call'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/optparse.rb:1391:in`block in parse_in_order'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/optparse.rb:1347:in `catch'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/optparse.rb:1347:in`parse_in_order'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/optparse.rb:1341:in `order!'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/optparse.rb:1432:in`permute!'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/optparse.rb:1453:in `parse!'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:574:in`handle_options'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:86:in `block in init'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:165:in`standard_exception_handling'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:84:in `init'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:76:in`block in run'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:75:in`run'
/Users/shaun/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
/Users/shaun/.rvm/gems/ruby-1.9.3-p448/bin/rake:23:in`load'
/Users/shaun/.rvm/gems/ruby-1.9.3-p448/bin/rake:23:in `<main>'
/Users/shaun/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in`eval'
/Users/shaun/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `<main>'
